//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int IdEmpleado { get; set; }
        public string Dni { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string Legajo { get; set; }
        public int IdTipoContrato { get; set; }
        public decimal Salario { get; set; }
        public decimal SalarioAnual { get; set; }        

        public void AsignarSalarioAnualEmpleado(Empleado empleado)
        {
            empleado.SalarioAnual = CalcularSalarioAnual(empleado.IdTipoContrato, empleado.Salario);
        }

        public void AsignarSalarioAnualEmpleados(List<Empleado> empleados)
        {
            foreach (var emp in empleados)
            {
                emp.SalarioAnual = CalcularSalarioAnual(emp.IdTipoContrato, emp.Salario);
            }
        }

        public decimal CalcularSalarioAnual(int idTipoContrato, decimal salario)
        {            

            switch (idTipoContrato)
            {
                case 1:

                    return 120 * salario * 12;

                case 2:

                    return salario * 12;

                default:

                    return 0;
            }
              
        }

    }
}
